# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FMDB'
  pod 'ZXingObjC', '~> 3.2.2'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'AFNetworking'
  pod 'SpinKit'
  pod 'ISMessages'
  pod 'IQKeyboardManagerSwift'
end
